### PR TITLE
Make scrubbers accessible

### PR DESCRIPTION
**Pull request by ctlusto**
- Add the thumb to the tab order
- Attach keyboard listeners for when the thumb is focused
- Add the ability to set a custom aria-label
- Set aria attributes when the scrubber updates

### CODE REVIEW

**Comment by ctlusto** [comment]
@jwmerrill Here's a stab at making scrubbers accessible. Might also be worth having Steve take a look at this before we merge it.

**Comment by jwmerrill** [comment]
Let's have @sclower  review this when he's back.

**Comment by jwmerrill** [comment]
Code looks great to me. Nice work.

**Comment by jwmerrill** [comment]
I'm going to go ahead and merge now, but would be interested in Steve's comments too.

**Comment by sclower** [comment]
Nice job. The only request I have is to have Page Up/Page Down move in larger step values, similar to what we do in our calculator.

**Comment by ctlusto** [comment]
There's something in my brain about @jwmerrill not liking how we do the "big step" thing in the calculator. It came up when I was working on sliders the first time around. Not sure whether (a) that's still true, (b) @sclower has a compelling argument, or (c) both _a_ and _b_.

But if you're both in agreement that we want big steps, by god we'll have big steps.

**Comment by jwmerrill** [comment]
I'm fine with big steps. You just have to be careful to not overshoot the min and max, and to also always land in the same places you would land with small steps.

This is especially tricky when the range (difference between min and max) is not an integer multiple of the step size. In the calculator, possible values increment by steps from the left until the first time you step past max; stepping past max clamps to max. So one big step lower than max is not in general  `max - big_step`.

**Comment by sclower** [comment]
Yeah, moving in larger increments with PGUP/DN is standard behavior with slider controls in Windows and also in the ARIA spec.

**Comment by ehberger** [comment]
Ping on getting this merged or closed.  Seems like it might be ready to just merge.

**Comment by ehberger** [comment]
Ping again to merge or close this.  @ctlusto @sclower @jwmerrill

**Comment by sclower** [comment]
@eberger to me, the keyboard usability still feels incomplete. Aside from hosting an open-source version of the slider control, are we planning on utilizing it in our own products? If we are, then I’d like to hold off until the accessibility work is done. Otherwise, we could release as is and leave it as an exercise for someone else to take on.

**Comment by ehberger** [comment]
Closing.  Feel free to re-open if anyone wants to take action on this.

**Pull request closed without merging**
